# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
        - '*'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        extension-csv: mbstring, xdebug
    - name: Add Plugin
      run: sudo apt install -y php7.3-xml
    - name: check php
      run: php -v
    - name: composer install
      run: |
        cd app
        composer install
    - name: ごにょごにょ
      run: |
        cd app
        php calculate.php
    - name: git setting
      run: |
        git config --local user.email "メールアドレスをここに入力"
        git config --local user.name "Githubのアカウントをここに入力"
    - name: Commit files
      run: |
        git add .
        git commit -m "Add csv" -a
        git pull
        git push origin master
